version: '3.4'
   
services:
    SqlServerDb:
        container_name: SqlServerContainer
        image: mcr.microsoft.com/mssql/server:2022-latest
        user: root
        # volumes:
        #   - db-data:/var/opt/mssql/data
        ports:
            - 8002:1433
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=Password123
    auth_ms_api:
        container_name: leare_auth_ms
        image: ${DOCKER_REGISTRY-}authmsapi
        ports:
            - 8001:80 
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:80;http://+:443
            - ASPNETCORE_Kestrel__Certificates__Default__Password=bfc0cfd8-b6f3-4fa2-9aa8-e21e7000023d
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        volumes:
            - ~/.aspnet/https:/https:ro
        build:
          context: .
          dockerfile: IdentityManagerServerApi/Dockerfile

        depends_on:
            - SqlServerDb 
volumes:
  db-data: